version: '3.8'

services:
  api:
    build:
      context: .
      target: ${ENVIRONMENT:-production}
    ports:
      - "8000:8000"
    environment:
      - APP_NAME=SoundPatch API
      - APP_DESCRIPTION=A FastAPI backend for SoundPatch application
      - APP_VERSION=1.0.0
      - DEBUG=${DEBUG:-false}
      - API_PREFIX=/api/v1
    volumes:
      - .:/app
      - uploads:/app/uploads
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  uploads:
  redis_data: 